config/routes.rb
Rails.application.routes.draw do
  #Devise Routes
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  #homepages routes
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  # blog
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #portfolio
  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'react-items', to: 'portfolios#react'

  # setting root path --> ex: localhost:3000/
  root to: 'pages#home'

end

app/models/blog.rb
class Blog < ApplicationRecord
  # enum
  enum status: { draft: 0, published: 1 }

  # Friendly edit
  extend FriendlyId
  friendly_id :title, use: :slugged

  # validations
  validates :title, :body, presence: true

  #Table Relationships
  belongs_to :topic, optional: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @pagy, @blogs = pagy(Blog.all, items: 5)
    @page_title = "Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      # my-blogs-post-:id gets handled by friendly and stored withing @blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.haml
.blog-post
  %h2.blog-post-title= link_to blog.title.upcase, blog
  %p.blog-post-meta
    Published #{distance_of_time_in_words(blog.created_at, Time.now)} ago
  - if logged_in?(:site_admin)
    %p.blog-post-meta
      = link_to blog.status, toggle_status_blog_path(blog)
      \/
      \#{link_to 'Edit', edit_blog_path(blog)} /
      \#{link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)}
  %p
    = blog.body

app/views/blogs/_form.html.haml
= form_with(model: blog, local: true) do |f|
  - if blog.errors.any?
    #error_explanation
      %h2
        = pluralize(blog.errors.count, "error")
        prohibited this blog from being saved:
      %ul
        - blog.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', rows: 16
  .form-group
    = f.submit class: 'btn btn-primary'

app/views/blogs/edit.html.haml
.col-sm-8.blog-main
  %h1 Editing Blog
  = render 'form', blog: @blog
  = link_to 'Show', @blog
  |
  = link_to 'Back', blogs_path

app/views/blogs/index.html.haml
.col-sm-8.blog-main
  = render @blogs
  != pagy_bootstrap_nav(@pagy).html_safe

app/views/blogs/new.html.haml
.col-sm-8.blog-main
  %h1 Test Blog
  = render 'form', blog: @blog
  = link_to 'Back', blogs_path

app/views/blogs/show.html.haml
.col-sm-8.blog-main
  %h2 
    = @blog.title
  = link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin)
  \/
  \#{link_to 'Back', blogs_path}
  %p
    = @blog.body