config/routes.rb
Rails.application.routes.draw do
  #Devise Routes
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  #homepages routes
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  # blog
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #portfolio
  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'react-items', to: 'portfolios#react'

  # setting root path --> ex: localhost:3000/
  root to: 'pages#home'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attributes| attributes['name'].blank? }
  acts_as_list

# validations
  validates :title, :body, :main_image, :thumb_image, presence: true

# custom scope
# first define class method
  def self.react
    where(subtitle: 'React')
  end

# scope and lambda
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

# automatically runs when initialization happens.
  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= "https://via.placeholder.com/600x400"
    self.thumb_image ||= "https://via.placeholder.com/350x200"
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy, :move]
  layout "portfolio"
  access all: [:show, :index, :react], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.all
  end

  def move
    @portfolio_item.insert_at(params[:position].to_i)
    head :ok
  end

  # custom scope
  def react
    @react_portfolio_items = Portfolio.react
  end

  def show
  end

  def new
    # new portfolio item is initialized.
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end 

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio Item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio Item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    # destroy the record
    @portfolio_item.destroy

    # redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body, 
                                      technologies_attributes: [:name]
                                    )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.haml
= form_for(@portfolio_item) do |f|
  .row
    .col-md-6
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :subtitle
        = f.text_field :subtitle, class: 'form-control'
    .col-md-6
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control', rows: 13
  %hr/
  .col-md-12
    %h2 Technolgies Used:
    %div
      = f.fields_for :technologies do |technology_form|
        .form-group
          = technology_form.label :name
          = technology_form.text_field :name, class: 'form-control'
    .form-group
      = f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block'

app/views/portfolios/_portfolio_item.html.haml
.card
  = image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?
  %p.card-text
    %span= link_to portfolio_item.title, portfolio_show_path(portfolio_item)
    = portfolio_item.subtitle

app/views/portfolios/edit.html.haml
.container.portfolio-form
  %h1 Edit this Portfolio Item
  = render 'form', portfolio_item: @portfolio_item

app/views/portfolios/index.html.haml
.album.text-muted
  .container
    .row
      = render partial: 'portfolio_item', collection: @portfolio_items
/ start of footer
%footer.text-muted
  .container
    %p.float-right
      %a{href: "#"} Back to top
    %p
      =@copyright
/ end of footer
  

app/views/portfolios/new.html.haml
.container.portfolio-form
  %h1 Create a new Portfolio Item
  = render 'form', portfolio_item: @portfolio_item

app/views/portfolios/react.html.haml
%h1 React Portfolio Items

= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin)

- @react_portfolio_items.each do |portfolio_item|
  %p
  = link_to portfolio_item.title, portfolio_show_path(portfolio_item)
  %p= portfolio_item.subtitle
  %p= portfolio_item.body
  = image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?
  = link_to "Edit Item", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin)
  = link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)

app/views/portfolios/show.html.haml
.container
  .row{style: " margin-top: 80px;"}
    .col-md-7
      = image_tag @portfolio_item.main_image
    .col-md-5
      %h1= @portfolio_item.title
      %hr/
      %em= @portfolio_item.subtitle
      %p= @portfolio_item.body
      %hr/
      %h3 Technologies Used:
      - @portfolio_item.technologies.each do |t|
        %p= t.name
    %footer.text-muted
    .container
      %p.float-right{style: " margin-top: 81px;"}
        = link_to "View All Portfolio Items", portfolios_path
      %p{style: " margin-top: 80px;"}
      =@copyright