config/routes.rb
Rails.application.routes.draw do
  #Devise Routes
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  #homepages routes
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  # blog
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #portfolio
  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'react-items', to: 'portfolios#react'

  # setting root path --> ex: localhost:3000/
  root to: 'pages#home'

end

app/views/shared/_application_nav.html.haml
%header.masthead.mb-auto
  .inner
    %h3.masthead-brand Danny Romero
    %nav.nav.nav-masthead.justify-content-center
      = link_to "Home", root_path, class: 'nav-link'
      = link_to "About Me", about_me_path, class: 'nav-link'
      = link_to "Contact", contact_path, class: 'nav-link'
      = link_to "Blog", blogs_path, class: 'nav-link'
      = link_to "Portfolio", portfolios_path, class: 'nav-link'
      = login_helper 'nav-link'
      

app/views/shared/_blog_footer.html.haml
%footer.blog-footer
  %p
    = @copyright
  %p
    %a{href: "#"} Back to top

app/views/shared/_blog_masthead.html.haml
.blog-header
  .container
    %h1.blog-title Danny's Blog
    = link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin)

app/views/shared/_blog_nav.html.haml
.blog-masthead
  .container
    %nav.nav.blog-nav
      = link_to "Home", root_path, class: 'nav-link'
      = link_to "About Me", about_me_path, class: 'nav-link'
      = link_to "Contact", contact_path, class: 'nav-link'
      = link_to "Portfolio", portfolios_path, class: 'nav-link'
      = login_helper 'nav-link'

app/views/shared/_blog_sidebar.html.haml
.col-sm-3.offset-sm-1.blog-sidebar
  .sidebar-module.sidebar-module-inset
    %h4 About
    %p
      Here you get a peak behind the curtain on what its like to job hunt.
  .sidebar-module
    %h4 Let's Connect!
    %ol.list-unstyled.social_links
      %li
        %a{href: "https://github.com/fdromero32", target: "_blank"}= fa_icon "github"
      %li
        %a{href: "https://www.linkedin.com/in/fdromero/", target: "_blank"}= fa_icon "linkedin"

app/views/shared/_navbar.html.haml
.location
  = link_to "Home", root_path, class: 'nav-link'
  = link_to "About Me", about_me_path, class: 'nav-link'
  = link_to "Contact", contact_path, class: 'nav-link'
  = link_to "Blog", blogs_path, class: 'nav-link'
  = link_to "Portfolio", portfolios_path, class: 'nav-link'